export const ShopRoute = '/shop'
export const HomeRoute = '/'
export const RegisterRoute = '/register' 
export const AuthRoute = '/authentication'
export const ContactRoute = '/contact'
export const NewsRoute = '/news'